---
abstract: 'The addition of topological sorting to DBIx::Class'
author:
  - '=over 4'
build_requires:
  ExtUtils::MakeMaker: 6.59
  List::MoreUtils: 0.01
  Test::DBIx::Class: 0.01
  Test::Deep: 0.01
  Test::Exception: 0.21
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: DBIx::Class::TopoSort
name: DBIx-Class-TopoSort
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0
  Graph: 0
  perl: 5.8.0
resources:
  IRC: irc://irc.perl.org/#dbix-class
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/dbix-class
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DBIx-Class-TopoSort
  homepage: http://search.cpan.org/perldoc?DBIx%3A%3AClass%3A%3ATopoSort
  license: http://dev.perl.org/licenses/
  repository: https://github.com/robkinyon/dbix-class-toposort
version: 0.050001
